import adapterVercel from "@sveltejs/adapter-vercel";
import adapterStatic from "@sveltejs/adapter-static";
import { vitePreprocess } from "@sveltejs/vite-plugin-svelte";

const isCapacitor = process.env.BUILD_TARGET === "cap";

/** @type {import('@sveltejs/kit').Config} */
const config = {
    preprocess: vitePreprocess(),
    kit: {
        adapter: isCapacitor
            ? adapterStatic({
                  pages: "build-cap",
                  assets: "build-cap",
                  fallback: "index.html",
                  precompress: false,
                  strict: false,
              })
            : adapterVercel({
                  runtime: "nodejs24.x",
              }),
        // rapper defines NO alias that leaves it — with no $lib/$generated, a child reaching for ReTreever fails to BUILD here instead of on a contractor's machine. Never re-add $lib or $generated to make an import resolve.
        alias: {
            // $parent/siblings — the flat folder holding every child, one level up in fetch/. The `../` lives HERE, never in an import.
            "$parent/siblings": "../",
            "$parent/siblings/*": "../*",

            // $parent = the mounting parent, whichever one it is — rapper and ReTreever each point it at THEMSELVES, so the same import lands in a different repo depending on which server runs.
            // Must stay an ALIAS, never a relative import — `../../rapper/...` names rapper and noEscapePlugin/noParentNames both fail it.
            // retreeved/ is GENERATED by gitEr/syncRetreeved.sh — edit the source in ReTreever, not here. app.css/app.unique.css are deliberately NOT copied (white here, violet there = how a page declares its tier).
            $parent: ".",
            "$parent/*": "./*",

        },
        // ⚠️ If rapper builds and emits NO pages, this routes path is wrong — SvelteKit does not error on a missing route tree, it silently serves nothing.
        // ⚠️ `routes` MUST STAY THE FIRST KEY, AND NO COMMENT MAY SIT BETWEEN `files: {` AND IT — the installer anchors on /files:\s*\{\s*routes:/ (create.mjs:305).
        files: {
            routes: "../getCache_OfflineMap/routes",
            // The child's param matchers — kit.files.params defaults to rapper's own (nonexistent) src/params, so without this a `[tab=searchTab]` route fails to build.
            params: "../getCache_OfflineMap/params",
            // The child's universal hooks — kit.files.hooks.universal defaults to rapper's own (nonexistent) src/hooks, so without this the hook silently never runs and "/" 404s.
            hooks: {
                universal: "../getCache_OfflineMap/hooks",
            },
        },
    },
};

export default config;
